config/routes.rb
Rails.application.routes.draw do
  resources :user_projects
  resources :artifacts

  resources :tenants do 
    resources :projects do
      get 'users', on: :member
      put 'add_user', on: :member
    end
  end
  resources :members
  get 'home/index'

  root to: "home#index"

  as(:user) do
    match '/user/confirmation' => 'confirmations#update', via: :put, as: :update_user_confirmation
  end

  devise_for :users, :controllers => {
    :confirmations => "confirmations",
    :registrations => "registrations"
  }

  match '/plan/edit' => 'tenants#edit', via: :get, as: :edit_plan
  match '/plan/update' => 'tenants#update', via: [:put, :patch], as: :update_plan

  # Page Not Found
  get "*path", to: "pages#not_found", constraints: lambda { |req| req.path.exclude? "rails/active_storage" }
end

app/models/user_project.rb
class UserProject < ApplicationRecord
  belongs_to :project
  belongs_to :user
end

app/controllers/user_projects_controller.rb
class UserProjectsController < ApplicationController
  before_action :set_user_project, only: %i[ show edit update destroy ]

  # GET /user_projects or /user_projects.json
  def index
    @user_projects = UserProject.all
  end

  # GET /user_projects/1 or /user_projects/1.json
  def show
  end

  # GET /user_projects/new
  def new
    @user_project = UserProject.new
  end

  # GET /user_projects/1/edit
  def edit
  end

  # POST /user_projects or /user_projects.json
  def create
    @user_project = UserProject.new(user_project_params)

    respond_to do |format|
      if @user_project.save
        format.html { redirect_to user_project_url(@user_project), notice: "User project was successfully created." }
        format.json { render :show, status: :created, location: @user_project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_projects/1 or /user_projects/1.json
  def update
    respond_to do |format|
      if @user_project.update(user_project_params)
        format.html { redirect_to user_project_url(@user_project), notice: "User project was successfully updated." }
        format.json { render :show, status: :ok, location: @user_project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_projects/1 or /user_projects/1.json
  def destroy
    @user_project.destroy

    respond_to do |format|
      format.html { redirect_to users_tenant_project_url(id: @user_project.project_id, tenant_id: @user_project.project.tenant_id), notice: "User was successfully removed from the project." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_project
      @user_project = UserProject.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_project_params
      params.require(:user_project).permit(:project_id, :user_id)
    end
end

app/helpers/user_projects_helper.rb
module UserProjectsHelper
end

app/views/user_projects/_form.html.erb
<%= form_with(model: user_project) do |form| %>
  <% if user_project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user_project.errors.count, "error") %> prohibited this user_project from being saved:</h2>

      <ul>
        <% user_project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :project_id, style: "display: block" %>
    <%= form.text_field :project_id %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/user_projects/_user_project.html.erb
<div id="<%= dom_id user_project %>">
  <p>
    <strong>Project:</strong>
    <%= user_project.project_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= user_project.user_id %>
  </p>

</div>

app/views/user_projects/edit.html.erb
<h1>Editing user project</h1>

<%= render "form", user_project: @user_project %>

<br>

<div>
  <%= link_to "Show this user project", @user_project %> |
  <%= link_to "Back to user projects", user_projects_path %>
</div>

app/views/user_projects/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>User projects</h1>

<div id="user_projects">
  <% @user_projects.each do |user_project| %>
    <%= render user_project %>
    <p>
      <%= link_to "Show this user project", user_project %>
    </p>
  <% end %>
</div>

<%= link_to "New user project", new_user_project_path %>

app/views/user_projects/new.html.erb
<h1>New user project</h1>

<%= render "form", user_project: @user_project %>

<br>

<div>
  <%= link_to "Back to user projects", user_projects_path %>
</div>

app/views/user_projects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user_project %>

<div>
  <%= link_to "Edit this user project", edit_user_project_path(@user_project) %> |
  <%= link_to "Back to user projects", user_projects_path %>

  <%= button_to "Destroy this user project", @user_project, method: :delete %>
</div>