config/routes.rb
Rails.application.routes.draw do
  resources :user_projects
  resources :artifacts

  resources :tenants do 
    resources :projects do
      get 'users', on: :member
      put 'add_user', on: :member
    end
  end
  resources :members
  get 'home/index'

  root to: "home#index"

  as(:user) do
    match '/user/confirmation' => 'confirmations#update', via: :put, as: :update_user_confirmation
  end

  devise_for :users, :controllers => {
    :confirmations => "confirmations",
    :registrations => "registrations"
  }

  match '/plan/edit' => 'tenants#edit', via: :get, as: :edit_plan
  match '/plan/update' => 'tenants#update', via: [:put, :patch], as: :update_plan

  # Page Not Found
  get "*path", to: "pages#not_found", constraints: lambda { |req| req.path.exclude? "rails/active_storage" }
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :tenant
  has_many :artifacts, dependent: :destroy
  validates_uniqueness_of :title
  validate :free_plan_can_only_have_one_project
  has_many :user_projects
  has_many :users, through: :user_projects

  def free_plan_can_only_have_one_project
    if self.new_record? && (tenant.projects.count > 0) && (tenant.plan == 'free')
      errors.add(:base, 'Free plans cannot have more than one project')
    end
  end

  def self.by_user_plan_and_tenant(tenant_id, user)
    tenant = Tenant.find(tenant_id)
    if tenant.plan == 'premium'
      if user.is_admin?
        tenant.projects
      else
        user.projects.where(tenant_id: tenant_id)
      end
    else
      if user.is_admin?
        tenant.projects.order(:id).limit(1)
      else
        user.projects.where(tenant_id: tenant_id).order(:id).limit(1)
      end
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy users add_user]
  before_action :set_tenant, only: [:show, :edit, :update, :destroy, :new, :create, :users, :add_user]
  before_action :verify_tenant

  # GET /projects or /projects.json
  def index
    @projects = Project.by_user_plan_and_tenant(params[:tenant_id], current_user)
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)
    @project.users << current_user

    respond_to do |format|
      if @project.save
        format.html { redirect_to root_url, notice: "Project was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to root_url(@project), notice: "Project was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to root_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def users
    # @project_users = (@project.users + (User.where(tenant: @tenant, is_admin: true))) - [current_user]
    @project_users = (@project.users + (User.joins(:tenants).where(is_admin: true, tenants: { id: @tenant.id}))) - [current_user]
    @other_users = @tenant.users.where(is_admin: false) - (@project_users + [current_user])
  end

  def add_user
    @project_user = UserProject.new(user_id: params[:user_id], project_id: @project.id)

    respond_to do |format|
      if @project_user.save
        format.html { redirect_to users_tenant_project_url(id: @project.id, tenant_id: @project.tenant_id), notice: 'User was successfully added to project' }
      else
        format.html { redirect_to users_tenant_project_url(id: @project.id, tenant_id: @project.tenant_id), error: 'User was not added to project' }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :details, :expected_completion_date, :tenant_id)
    end

    def set_tenant
      @tenant = Tenant.find(params[:tenant_id])
    end

    def verify_tenant
      # unless params[:tenant_id] == Tenant.current_tenant_id.to_s
      unless params[:tenant_id] == current_tenant.id.to_s
        redirect_to :root, flash: {error: "You are not authorized to access any organization other than your own"}
      end
    end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: [@tenant, @project], html: {class: "form-horizontal project"}) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group mb-3">
    <%= form.label :title, style: "display: block", class: "control-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="control-group mb-3">
    <%= form.label :details, style: "display: block", class: "control-label"  %>
    <%= form.text_field :details, class: "form-control"  %>
  </div>

  <div class="control-group mb-3">
    <%= form.label :expected_completion_date, style: "display: block", class: "control-label"  %>
    <%= form.date_field :expected_completion_date, class: "form-control"  %>
  </div>

  <%= form.hidden_field :tenant_id, value: params[:tenant_id], class: 'form-control' %>
  
  <div>
    <%= form.submit nil, class: 'btn btn-primary' %>
    <%= link_to t('.cancel', default: t("helpers.links.cancel")), root_path, class: 'btn btn-outline-primary' %>
  </div>

  
<% end %>

app/views/projects/_list.html.erb
<h1>Projects</h1>

<% if @projects.size > 0 %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Title</th>
        <th>Details</th>
        <th>Expected Completion Date</th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @projects.each do |project| %>
        <tr>
          <td class="align-middle"><%= link_to project.title, tenant_project_path(project, tenant_id: @tenant.id), class: 'main-link' %></td>
          <td class="align-middle"><%= project.details %></td>
          <td class="align-middle"><%= project.expected_completion_date %></td>
          <td>
            <div class="d-flex">
              <%= link_to 'Edit', edit_tenant_project_path(project, tenant_id: @tenant.id), class: 'btn btn-outline-primary btn-xs me-2' %>
              <%= link_to 'Edit Users', users_tenant_project_path(project, tenant_id: @tenant.id), class: 'btn btn-outline-primary btn-xs me-2' %>
              <%= button_to "Destroy", tenant_project_path(project, tenant_id: @tenant.id), method: :delete, class:"btn btn-danger btn-xs" %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p class="lead">You don't have any projects</p>
<% end %>

<% if (@tenant.can_create_project?) %>
  <%= link_to "New project", new_tenant_project_path(tenant_id: current_tenant.id), class: "btn btn-primary" %>
<% else %>
  <%= link_to "New project", new_tenant_project_path(tenant_id: current_tenant.id), class: "btn btn-secondary disabled" %>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">

  <h3><%= project.title %></h3>
  <h3><small>Organization - <%= tenant_name project.tenant_id %></small></h3>

  <table class="mb-2">
    <tbody>
      <tr>
        <td><strong>Title:</strong></td>
        <td><%= project.title %></td>
      </tr>
      <tr>
        <td><strong>Details:</strong></td>
        <td><%= project.details %></td>
      </tr>
      <tr>
        <td><strong>Expected completion date:</strong></td>
        <td><%= project.expected_completion_date %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", tenant_project_path %> |
</div>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form", project: @project %>

<br>

app/views/projects/show.html.erb
<%# <%= render @project %> 
<div>
<%# <div id="<%= dom_id project %>

  <h3><%= @project.title %></h3>
  <h3><small>Organization - <%= tenant_name @project.tenant_id %></small></h3>

  <table class="mb-2">
    <tbody>
      <tr>
        <td><strong>Title:</strong></td>
        <td><%= @project.title %></td>
      </tr>
      <tr>
        <td><strong>Details:</strong></td>
        <td><%= @project.details %></td>
      </tr>
      <tr>
        <td><strong>Expected completion date:</strong></td>
        <td><%= @project.expected_completion_date %></td>
      </tr>
    </tbody>
  </table>
</div>

<p>
  <h3>Artifacts</h3>
  <%= render 'artifacts/list', artifacts: @project.artifacts %>
</p>

<div class="d-flex">
    <%= link_to "< Back to Organization Home", root_path, class:"btn btn-outline-primary me-2" %>
    <%= link_to "Edit this project", edit_tenant_project_path(project: @project, tenant: @project.tenant_id), class:"btn btn-outline-primary me-2" %>
    <%= link_to "Edit Project Users", users_tenant_project_path(tenant_id: @project.tenant_id, id: @project.id), class: "btn btn-outline-primary me-2" %>
    <%= button_to "Destroy this project", tenant_project_path(@project, tenant_id: @project.tenant_id), method: :delete, class:"btn btn-outline-danger" %>
</div>

app/views/projects/users.html.erb
<div class="page-header">
    <h3>Users for Project <%= @project.title %></h3>
    <strong>(Other than yourself)</strong>
</div>
<table class="table table-striped">
    <thead>
        <tr>
            <th> Email </th>
            <th> <%= t '.actions', default: t("helpers.actions") %> </th>
        </tr>
    </thead>
    <tbody>
        <% @project_users.each do |project_user| %>
            <tr>
                <td><%= project_user.email%></td>
                <td>
                    <% if !project_user.is_admin? %>
                        <%= button_to "Remove", user_project_path(project_user.user_projects.find_by(project_id: @project.id), tenant_id: @project.tenant_id), 
                                            method: :delete, 
                                            data: { confirm: t('.confirm', default: t('helpers.links.confirm', default: 'Are you sure?'))}, 
                                            class: 'btn btn-xs btn-danger' %>
                    <% end %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

<h3>Users to add to Project <%= @project.title %></h3>
<strong>(Admins don't need to be added)</strong>
<table class="table table-striped">
    <thead>
        <tr>
            <th> Email </th>
            <th> <%= t '.actions', default: t("helpers.actions") %> </th>
        </tr>
    </thead>
    <tbody>
        <% @other_users.each do |other_user| %>
            <tr>
                <td><%= other_user.email%></td>
                <td>
                    <%= button_to "Add", add_user_tenant_project_path(id: @project.id, tenant_id: @project.tenant_id, user_id: other_user.id), 
                                        method: :put, 
                                        class: 'btn btn-xs btn-danger' %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

<%= link_to 'Back', tenant_project_path(id: @project.id, tenant_id: @project.tenant_id), class: 'btn btn-primary' %>