config/routes.rb
Rails.application.routes.draw do
  resources :user_projects
  resources :artifacts

  resources :tenants do 
    resources :projects do
      get 'users', on: :member
      put 'add_user', on: :member
    end
  end
  resources :members
  get 'home/index'

  root to: "home#index"

  as(:user) do
    match '/user/confirmation' => 'confirmations#update', via: :put, as: :update_user_confirmation
  end

  devise_for :users, :controllers => {
    :confirmations => "confirmations",
    :registrations => "registrations"
  }

  match '/plan/edit' => 'tenants#edit', via: :get, as: :edit_plan
  match '/plan/update' => 'tenants#update', via: [:put, :patch], as: :update_plan

  # Page Not Found
  get "*path", to: "pages#not_found", constraints: lambda { |req| req.path.exclude? "rails/active_storage" }
end

app/models/artifact.rb
class Artifact < ApplicationRecord

  before_save :upload_to_s3
  attr_accessor :upload
  belongs_to :project

  MAX_FILE_SIZE = 10.megabytes
  validates_presence_of :name, :upload
  validates_uniqueness_of :name

  validate :uploaded_file_size

  private

  def upload_to_s3
    s3 = Aws::S3::Resource.new
    # tenant_name = Tenant.find(Thread.current[:tenant_id]).name
    tenant_name = self.project.tenant.name
    obj = s3.bucket(ENV['S3_BUCKET']).object("#{tenant_name}/#{upload.original_filename}")
    # obj.upload_file(upload.path, acl:'public-read')
    obj.upload_file(upload.path)
    self.key = obj.public_url
  end

  def uploaded_file_size
    if upload
      errors.add(:upload, "File size must be less than #{self.class::MAX_FILE_SIZE}") unless upload.size <= self.class::MAX_FILE_SIZE
    end
  end

end

app/controllers/artifacts_controller.rb
class ArtifactsController < ApplicationController
  before_action :set_artifact, only: %i[ show edit update destroy ]

  # GET /artifacts or /artifacts.json
  def index
    @artifacts = Artifact.all
  end

  # GET /artifacts/1 or /artifacts/1.json
  def show
  end

  # GET /artifacts/new
  def new
    @artifact = Artifact.new
    @artifact.project_id = params[:project_id]
  end

  # GET /artifacts/1/edit
  def edit
  end

  # POST /artifacts or /artifacts.json
  def create
    @artifact = Artifact.new(artifact_params)

    respond_to do |format|
      if @artifact.save
        format.html { redirect_to tenant_project_url(tenant_id: current_tenant.id, id: @artifact.project_id), notice: "Artifact was successfully created." }
        format.json { render :show, status: :created, location: @artifact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @artifact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artifacts/1 or /artifacts/1.json
  def update
    respond_to do |format|
      if @artifact.update(artifact_params)
        format.html { redirect_to artifact_url(@artifact), notice: "Artifact was successfully updated." }
        format.json { render :show, status: :ok, location: @artifact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @artifact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artifacts/1 or /artifacts/1.json
  def destroy
    @artifact.destroy

    respond_to do |format|
      format.html { redirect_to tenant_project_url(tenant_id: current_tenant.id, id: @artifact.project_id), notice: "Artifact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artifact
      @artifact = Artifact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def artifact_params
      params.require(:artifact).permit(:name, :upload, :project_id)
    end
end

app/helpers/artifacts_helper.rb
module ArtifactsHelper
end

app/views/artifacts/_artifact.html.erb
<div id="<%= dom_id artifact %>">
  <p>
    <strong>Name:</strong>
    <%= artifact.name %>
  </p>

  <p>
    <strong>Key:</strong>
    <%= artifact.key %>
  </p>

  <p>
    <strong>Project:</strong>
    <%= artifact.project_id %>
  </p>

</div>

app/views/artifacts/_form.html.erb
<%= form_with(model: artifact) do |form| %>
  <% if artifact.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(artifact.errors.count, "error") %> prohibited this artifact from being saved:</h2>

      <ul>
        <% artifact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= form.label :name, style: "display: block", class: "control-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="control-group">
    <%= form.label :upload, value: 'File to upload', style: "display: block", class: "control-label" %>
    <%= form.file_field :upload, class: "form-control" %>
  </div>

  <%= form.hidden_field :project_id %>

  <div class="mt-2">
    <%= form.submit nil, class: "btn btn-primary" %>
    <%= link_to 'Cancel', tenant_project_path(tenant_id: current_tenant.id, id: @artifact.project_id), class: 'btn btn-outline-primary' %>
  </div>
<% end %>

app/views/artifacts/_list.html.erb
<table class="table table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Key</th>
            <th><%=t '.actions', :default => t("helpers.actions") %></th>
        </tr>
    </thead>
    <tbody>
        <% artifacts.each do |artifact| %>
            <tr>
                <td class="align-middle"><%= link_to artifact.name, artifact_path(artifact), class: 'main-link' %></td>
                <td class="align-middle"><%= s3_link current_tenant.id, artifact.key %></td>
                <td class="align-middle">
                    <%= button_to 'Destroy', artifact_path(artifact), method: :delete, class: 'btn btn-xs btn-danger'%>
                    <%# link_to t('.destroy', :default => t("helpers.links.destroy")),
                                artifact_path(artifact),
                                :method => :delete,
                                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                                :class => 'btn btn-xs btn-danger' %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

<%= link_to 'New Artifact', new_artifact_path(project_id: @project.id), class: 'btn btn-primary' %>

app/views/artifacts/edit.html.erb
<h1>Editing artifact</h1>

<%= render "form", artifact: @artifact %>

<br>

<div>
  <%= link_to "Show this artifact", @artifact %> |
  <%= link_to "Back to artifacts", artifacts_path %>
</div>

app/views/artifacts/index.html.erb
<h1>Artifacts</h1>

<%= render 'artifacts/list', artifacts: @project.artifacts %>

app/views/artifacts/new.html.erb
<h1>New artifact</h1>

<%= render "form", artifact: @artifact %>

<br>

<div>
  <%= link_to "Back to artifacts", artifacts_path %>
</div>

app/views/artifacts/show.html.erb
<%= render @artifact %>

<div>
  <%= link_to "Edit this artifact", edit_artifact_path(@artifact) %> |
  <%= link_to "Back to artifacts", artifacts_path %>

  <%= button_to "Destroy this artifact", @artifact, method: :delete %>
</div>