config/routes.rb
Rails.application.routes.draw do
  resources :user_projects
  resources :artifacts

  resources :tenants do 
    resources :projects do
      get 'users', on: :member
      put 'add_user', on: :member
    end
  end
  resources :members
  get 'home/index'

  root to: "home#index"

  as(:user) do
    match '/user/confirmation' => 'confirmations#update', via: :put, as: :update_user_confirmation
  end

  devise_for :users, :controllers => {
    :confirmations => "confirmations",
    :registrations => "registrations"
  }

  match '/plan/edit' => 'tenants#edit', via: :get, as: :edit_plan
  match '/plan/update' => 'tenants#update', via: [:put, :patch], as: :update_plan

  # Page Not Found
  get "*path", to: "pages#not_found", constraints: lambda { |req| req.path.exclude? "rails/active_storage" }
end

app/views/layouts/_footer.html.erb
<body class="d-flex flex-column">
  <div id="page-content">
   
  </div>
  <footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white-50">
    <div class="container text-center">
      <small>Copyright &copy; 
        <%= Time.now.year %> <%= link_to 'My Project Management App', root_path %> All Rights Reserved. Made by Harsh Kumar
    </div>
  </footer>
</body>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3 mb-4">
  <div class="container">

    <%= link_to ("<i class='my-icon fas fa-project-diagram'></i> Project Management App").html_safe, root_path, class: 'navbar-brand' %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if current_user && current_user.is_admin? %>
          <li class="nav-item">
            <%= link_to "<i class='fa fa-users'></i> Add Members".html_safe, new_member_path, class: 'navbar-link btn btn-primary me-2' %>
          </li>
          <li class="nav-item">
            <%= link_to "<i class='fa fa-briefcase'></i> Change Plan".html_safe, edit_plan_path, class: 'btn btn-primary navbar-link' %>
          </li>
        <% end %>
      </ul>
      <div class="d-flex">
      <ul class="navbar-nav">
        <% if current_user %>
          <li class="col-md-9 nav-item">
            <%= link_to ('<i class="fa fa-user"></i> ' + truncate(current_user.email, length: 25)).html_safe, edit_user_registration_path, title: 'Edit Profile', class: 'nav-link' %>
          </li>
          <li class="col-md-3 logout">
            <%= button_to 'Logout', destroy_user_session_path, class:'btn btn-danger', method: :delete, data: { turbo: false } %>
          </li>
        <% else %>
          <li>
            <%= link_to('Login', new_user_session_path, class: 'btn btn-primary') %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SaasProjectApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# Font Awesome %>
    <link rel="stylesheet" data-purpose="Layout StyleSheet" title="Default" disabled
    href="/css/app-af6a05f42b013986b481566363f0186f.css?vsn=d" />
    <link rel="stylesheet" data-purpose="Layout StyleSheet" title="Web Awesome"
    href="/css/app-wa-df1bd4d47fc6bf066625b27b61ccafe7.css?vsn=d" />
    <link rel="stylesheet" href="https://site-assets.fontawesome.com/releases/v6.3.0/css/all.css" />
    <link rel="stylesheet" href="https://site-assets.fontawesome.com/releases/v6.3.0/css/sharp-solid.css" />
    <link rel="stylesheet" href="https://site-assets.fontawesome.com/releases/v6.3.0/css/sharp-regular.css" />
    <%= javascript_include_tag "https://js.stripe.com/v2/" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= yield :head %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>